export enum ActivityStatus {
    CREATING, OPENED, 
	IN_PROGRESS, RESOLVED, UPDATING, REOPENING, CANCELLING, CLOSING, CLOSED, 
	ERRORED, ERRORED_ON_CREATE, ERRORED_ON_UPDATE, ERRORED_ON_REOPEN, ERRORED_ON_CLOSE,NOT_OPEN,NOT_CLOSED,PENDING_FOR_ATTACHMENT 
}