export const labelsMapping = {
    suspected_outage: 'Suspected Outage',
    is_fcr_complaint: 'Is FCR Complaint',
    prefered_languages: 'Preferred Language',
    extension_no: 'Extension No',
    mobile_device_type: 'Mobile Device Type',
    customer_id_type: 'Customer ID',
    partner_name_type: 'Partner Name',
    complaint_capture_type: 'Complaint Capture Type',
    activity_desc: 'Complaint Description',
    region: 'Region',
    reporting_channel: 'Reporting Channel',
    priority_flag: 'Priority Flag',
    dispute_amount: 'Dispute Amount',
    refund_amount: 'Refund Amount',
    new_mobile_no: 'New Mobile Number',
    sim_serial_no: 'SIM Serial Number',
    femto_device_no: 'Device Number',
    femto_serial: 'Serial Number',
    femto_dp: 'Distribution Point(DP)',
    femto_mdf: 'Exchange Code(MDF)',
    femto_cell_id: 'Cell ID',
    femto_location: 'Location',
    femto_flat: 'Flat',
    femto_network_type: 'Network Type',
    gis_location: 'GIS Location',
    attachments: 'Attachments',
    attachments_tab_header: 'Attachments',
    contacts: 'Contacts',
    contacts_tab_header: 'Contacts',
    special_fields: 'Special Fields',
    special_fields_header: 'Special Fields',
    followups: 'Remarks History',
    followups_header: 'Complaint Remarks History',
    neglect_ecd: 'Neglect ECD?',
    charge_code: 'Charge Code *',
    adjustment_date: 'Adjustment Date *',
    adjustment_remarks: 'Remarks *',
    adjustment_amount: 'Amount *',
    contact_details: 'Contact Details *',
    contact_number: 'Contact Number *',
    mobile_number: 'Mobile Number *',
    contact_email: 'Contact Email',
    prefered_language: 'Preferred Language *',
    adjustmen_region: 'Region *',
    adjustment_type: 'Cause of Refund *',
    internet_availablity: 'Internet Availablity',
    internet_number: 'Internet Number',
    new_mobile_party_id: 'Party ID',
    new_mobile_retailer_name: 'Retailer Name',
    new_mobile_number: 'New Mobile Number',
    new_mobile_serial: 'New Mobile Serial',
    registered_date: 'Registered Date',
    activity_remarks: 'Remarks',
    previous_activity_remarks: 'Previous Remarks'
};
